### ISSUE TITLE
Why a .env

### ISSUE THREAD

**Issue by Muffl0n-DE** [fernwerker/ownDynDNS#10]
Wieso verwendest du eine .env?

Die .env ist bei Standardeinstellungen am Server über den Browser aufrufbar. 
Wenn du die Variablen in einer PHP-Datei festlegst, wäre das sicherer

**Comment by b2un0** [comment]
keine lust auf Englisch: Was?

im `.env` File stehen die API Credentials von netcup, möchtest du diese wirklich per `_GET` vom Router an das Script übertragen? Ich nicht.

**Comment by Muffl0n-DE** [comment]
Hab mal kurz ins lesbare übersetzt

**Comment by b2un0** [comment]
ahhhh, nun verstehe ich das.

Die `.env` hab ich beim PR eingeführt, das ist bei mir eine Gewohnheit durch Symfony.

Jetzt wo du es sagst, hatte nicht daran gedacht das man die selber schützen muss, für Apache z.B. so via `.htaccess`:

```
<Files .env>
    Order allow,deny
    Deny from all
</Files>
```

Es steht dir frei einen PR zu eröffnen damit es z.B. eine `env.php` wird :)

**Comment by Muffl0n-DE** [comment]
Leider hab ich nicht genug Ahnung von PHP. Ist schon Jahre her seitdem ich das Letzt mal was damit gemacht habe.
Ich würde da nur die nächste Lücke reinhauen :D

**Comment by fernwerker** [comment]
solved by #11
