### ISSUE TITLE
run as cronjob on a **nix based device

### ISSUE THREAD

**Issue by julianheusel** [fernwerker/ownDynDNS#13]
Guten Abend,
ein Kumpel und ich sind auf Ihr GitHub repository ownDynDNS gestossen und sind von der Idee wirklich sehr begeistert.
Die readme konnten wir ohne Probleme abarbeiten. Leider kommen wir beim Punkt „run as cronjob on a **nix based device“ nicht weiter.
 
Was genau müssen wir als Cronjonb ausführen?
In welchen Abständen soll der Cronjob die Aufgabe ausführen?
 
Wir verwenden ein Netcup Webhosting 2000.
 
Besten Dank für die Idee und Entwicklung. Über eine Auskunft zu unserem Problem, würden wir uns sehr freuen.
 
Viele Grüße
Julian

**Comment by fernwerker** [comment]
Hallo Julian,
freut mich sehr, dass Euch das Tool gefällt.
Ich muss vielleicht in der Readme ein wenig anpassen. Man muss das Tool vielleicht ein bisschen zwischen DynDNS Service und den Beispielen für Clients unterscheiden.
Das "run as cronjob.." und die dazugehörigen "examples" auf die Ihr gestoßen seid, sind für Geräte innerhalb eures Netzwerks (bspw. ein NAS oder ähnliches). Diese können ebenfalls zur Meldung der aktuellen IP-Adresse genutzt werden (insbesondere für IPv6 natürlich hilfreich, da die meisten Router nur ihre eigene Adresse melden).
Wenn ihr bei netcup alles andere untergebracht habt und ihr habt eine Fritzbox, dann schaut mal, ob alles funktioniert.
Beste Grüße,
Felix

-- for english speakers:
the issue refers to the mentioned unix examples and the according cronjob to have additional devices within your network to also publish the current IP address to the dynDNS service.

**Comment by julianheusel** [comment]
Guten Abend Felix,
vielen Dank für diesen Hinweis! Wir konnten alles erfolgreich einrichten. Wirklich eine geniale Idee und Umsetzung 👍

Beste Grüße
Julian
