### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by alandolsi** [fernwerker/ownDynDNS#14]
I get this error when I execute update.php
PHP Fatal error:  Uncaught RuntimeException: payload invalid in ownDynDNS/src/Handler.php:35
can you tell me why?!

"[2020-12-15T20:56:14+00:00] api login successful",
"[2020-12-15T20:56:14+00:00] dns recordset NOT updated (no changes)",
"[2020-12-15T20:56:14+00:00] api logout successful",

Thank you

**Comment by fernwerker** [comment]
Did you create the A record in advance? The tool will only update existing records. So you need to create it with an invalid IP address first.

**Comment by alandolsi** [comment]
thank you Felix, that was the problem.
