### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by Schmide-github** [fernwerker/ownDynDNS#16]
Hi,

ist es möglich gleich mehrere Subdomains zu aktualisieren ohne mehrfach das Script mit verschiedenen Namen aufzurufen?

Gruß

**Comment by Schmide-github** [comment]
Mit der gleichen IP, das wäre super wenn das funktionieren würde.

**Comment by fernwerker** [comment]
Naja, dafür braucht es das Skript nicht. Bei DNS gibt es dafür die CNAME Einträge die sich bestens dafür eignen, da nur ein Eintrag die IP hat (= A oder AAAA Eintrag) und die CNAMEs zeigen auf diesen. 

Vorteil: die IP muss auch immer nur an einem Eintrag aktualisiert werden

**Comment by Schmide-github** [comment]
dachte es kann Probleme mit dem MX geben.

server.dom A 1.2.3.4
mail.dom CNAME server.dom
@ MX mail.dom

Dachte das darf so nicht sein, kann mich aber jetzt auch irren...

**Comment by fernwerker** [comment]
Wüsste nicht, warum das n Problem machen sollte und bei mir läuft das so ohne Weiteres.

closed
