### ISSUE TITLE
Aktualisierung funktioniert nicht

### ISSUE THREAD

**Issue by Wolf6660** [fernwerker/ownDynDNS#19]
Hi, 

ich habe wie du geschrieben hast alles auf den Webserver kopiert und die Datei .env bearbeitet. Auf der FritzBox habe ich dann die URL sowie die Benutzername und Passwort eingegeben. 

Das bekomme ich als Rückmeldung:
GET /update.php?user=USERNAME&password=PASSWORD&ipv4=MEINE-IP&ipv6=&domain=SUB.DOMAIN.DE HTTP/1.0

Wenn ich nun die Subdomain anpinge bekomme ich nicht meine IP angezeigt.

Was mache ich falsch? Habe ich etwas übersehen?

Danke

**Comment by Wolf6660** [comment]
Hi,

wenn ich eine nslookup mache bekomme ich wie beim ping auch die IP vom Netcup Server angezeigt. Sollte sich aber meine sein oder?

danke

**Comment by b2un0** [comment]
richtig gut ist, wenn man alle Fragen beantwortet, die einem gestellt werden.

**Comment by Wolf6660** [comment]
ja klar habe ich die Subdomain angelegt, sonst könnte ich diese ja nicht anpingen bzw. einen nslookup absetzten.

**Comment by fernwerker** [comment]
Doch kann möglich sein, da netcup standardmäßig wildcards anlegt. Wenn du die also nicht gelöscht hast löst jede Domain auf deinen Webspace auf.

**Comment by fernwerker** [comment]
Und SUB.DOMAIN.de ist als A record im CCP angelegt?

Was für eine IP Adresse steht denn dann in dem A record von SUB.DOMAIN.de?

**Comment by Wolf6660** [comment]
Hi, 

sorry damit ich mich so spät melde. Das habe ich vergessen. Danke

Wenn ich das mache dauert es ca. 5min bis die Subdomain mit der neuen IP erreichbar ist. Der DNS Eintrag ist aber sofort drin. Ist dies normal?

Sorry für die blöden Fragen. Bin da nicht so fit in dem Thema.

Danke

**Comment by fernwerker** [comment]
Ich hab das README mal aktualisiert, denn darauf bezieht sich: 
> Create each host record in your netcup CCP before using the script. The script does not create any missing records.
Alles andere muss nicht erstellt werden. Es ist ja nur DNS entscheidend und kein Webspace erforderlich.

Die Zeit ist abhängig von der TTL (time to live) Einstellung. Allerdings ist DNS von Natur aus ein "träges" System und das ist gewollt bzw. korrekt so. Ein niedriger Wert erhöht die Aktualisierungslast, da viel Server diese Informationen cachen.

Ich nutz DynDNS mit meiner Fritzbox und lasse diese nachts (3-4 Uhr) die Zwangstrennung machen. Somit ist die IP immer aktuell wenn ich sie brauche.

Thema closed.
