### ISSUE TITLE
DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler 500 - Internal Server Error

### ISSUE THREAD

**Issue by Doerchen** [fernwerker/ownDynDNS#2]
Hello.

Since 2 weeks I get the following error on several FritzBox devices using this script:
"_**DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler 500 - Internal Server Error**_"
The time before it runs without problems… (I did not change anything in my Website)

So what can I do to solve this Problem?
 
Best regards
Doerchen

**Comment by fernwerker** [comment]
Hi,
can you send me the content of http://yourdomain.com/data.json
Please place a file like "test.php" containing in the same folder as the update.php:
```
<?php
echo("DynDNS Test");
?>
```
Call it via: http://yourdomain.com/test.php and tell me if the result is "DynDNS Test".

I assume an error in the webserver of domain config inside the fritzbox, because the 500 is triggered by the webserver. So more details for debugging can be found in the webserver log.

**Comment by Doerchen** [comment]
Here is content of data.json…

 

{"FritzBox.nethawk.de":{"log":["valid IPv4","valid IPv6","dns recordset updated","api logout"],"failed_logins":0,"timestamp":1543150622,"ipv4":"87.123.106.118","ipv6":"2001:16b8:6501:bd27:e228:6dff:fe46:dbcc"},"BigfoodUM.nethawk.de":{"log":["valid IPv4","valid IPv6","dns recordset updated","api logout"],"failed_logins":0,"timestamp":1543151328,"ipv4":"84.118.3.65","ipv6":"2a02:908:2a00:4:868:3d91:97a6:2b3b"}}

 

Best regards

 

Von: Felix Kretschmer [mailto:notifications@github.com] 
Gesendet: Sonntag, 25. November 2018 01:01
An: fernwerker/ownDynDNS <ownDynDNS@noreply.github.com>
Cc: Doerchen <darek.abessinier@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [fernwerker/ownDynDNS] DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler 500 - Internal Server Error (#2)

 

Hi,
can you send me the content of http://yourdomain.com/data.json
Please place a file like "test.php" containing in the same folder as the update.php:

<?php
echo("DynDNS Test");
?>

Call it via: http://yourdomain.com/test.php and tell me if the result is "DynDNS Test".

I assume an error in the webserver of domain config inside the fritzbox, because the 500 is triggered by the webserver. So more details for debugging can be found in the webserver log.

**Comment by Doerchen** [comment]
Hi.

 

Can you explain me what kind of operator is „->“

 

(sample: $record->destination)

 

Best regards

 

Von: Felix Kretschmer [mailto:notifications@github.com] 
Gesendet: Sonntag, 25. November 2018 01:01
An: fernwerker/ownDynDNS <ownDynDNS@noreply.github.com>
Cc: Doerchen <darek.abessinier@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [fernwerker/ownDynDNS] DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler 500 - Internal Server Error (#2)

 

Hi,
can you send me the content of http://yourdomain.com/data.json
Please place a file like "test.php" containing in the same folder as the update.php:

<?php
echo("DynDNS Test");
?>

Call it via: http://yourdomain.com/test.php and tell me if the result is "DynDNS Test".

I assume an error in the webserver of domain config inside the fritzbox, because the 500 is triggered by the webserver. So more details for debugging can be found in the webserver log.

**Comment by Doerchen** [comment]
Darek möchte die Nachricht "[fernwerker/ownDynDNS] DynDNS-Fehler: Der
DynDNS-Anbieter meldet Fehler 500 - Internal Server Error (#2)" zurückrufen.

**Comment by Doerchen** [comment]
I think you are right. 

Problem is on netcup webserver…

So I’ll try the same.

As I said netcup restored my CCP domain from backup on 15.11.2018…

 

Von: Felix Kretschmer [mailto:notifications@github.com] 
Gesendet: Sonntag, 25. November 2018 17:23
An: fernwerker/ownDynDNS <ownDynDNS@noreply.github.com>
Cc: Doerchen <darek.abessinier@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [fernwerker/ownDynDNS] DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler 500 - Internal Server Error (#2)

 

The -> is used to access methods and properties of an object.

Is your subdomain created in the netcup CCP domain properties? I don't know where your problem is. But must be on the netcup webserver side. Without changing anything it is running on my webspace and I got the record dump problem as well.
Setting back to default and adding my dyndns subdomains everything works fine now.

**Comment by Doerchen** [comment]
It looks like resetting netcup CCP domain properties solved my problems too…

 

Thank you for support.

 

Best regards

Darek

 

Von: Felix Kretschmer [mailto:notifications@github.com] 
Gesendet: Sonntag, 25. November 2018 17:23
An: fernwerker/ownDynDNS <ownDynDNS@noreply.github.com>
Cc: Doerchen <darek.abessinier@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [fernwerker/ownDynDNS] DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler 500 - Internal Server Error (#2)

 

The -> is used to access methods and properties of an object.

Is your subdomain created in the netcup CCP domain properties? I don't know where your problem is. But must be on the netcup webserver side. Without changing anything it is running on my webspace and I got the record dump problem as well.
Setting back to default and adding my dyndns subdomains everything works fine now.

**Comment by fernwerker** [comment]
Cool. Perfect. Have fun with the script.
