### ISSUE TITLE
Sporadisch kein DNS Record Update

### ISSUE THREAD

**Issue by scripthase** [fernwerker/ownDynDNS#26]
Hallo zusammen,

ich habe seit mehreren Jahren das PHP-Skript am Laufen für DynDNS von Netcup mit einer Fritz!Box.

Seit einiger Zeit tritt immer wieder das Problem auf, dass bei einer Aktualisierung der IP vom Internetanbieter, dass Skript die neue IP in den DNS-Records einträgt, aber nur den Record "@" und nicht "*" .

Bis vor kurzer Zeit hat er immer beide identisch gesetzt.

Dadurch, dass das * nicht aktualisiert wird, kommt es dann immer dazu, dass Subdomains nicht erreichbar sind.

Ist das Problem bekannt und gibt es hier eine Lösung für?

Vielen lieben Dank schon Mal!

Liebe Grüße
Scripthase

**Comment by b2un0** [comment]
Wenn Du das Script nicht ausgetauscht hast, und es seit Jahren das gleiche ist, dann würde ich eher auf einen Fehler in der Netcup API tippen.
Bei mir läuft [meine Version](https://github.com/b2un0/docker-netcup-dyndns) als Docker Container seit Jahren fehlerfrei.

**Comment by b2un0** [comment]
Vielleicht sollte ich die Container Änderung mal hierhin zurückführen.. 🤔

**Comment by scripthase** [comment]
> Wenn Du das Script nicht ausgetauscht hast, und es seit Jahren das gleiche ist, dann würde ich eher auf einen Fehler in der Netcup API tippen. Bei mir läuft [meine Version](https://github.com/b2un0/docker-netcup-dyndns) als Docker Container seit Jahren fehlerfrei.

Hmm, komisch. Kann man das Problem irgendwie beheben? Ich will jetzt nicht extra einen Docker Container einrichten für das DynDNS. :(

**Comment by NiiWiiCamo** [comment]
Schonmal die debug logs angeschaltet?
mode=both ist vermutlich ja in der URL gesetzt, vielleicht kann man da die logs noch ein bisschen verboser gestalten.

**Comment by NiiWiiCamo** [comment]
Alternativ auch mal den force=true parameter in die URL setzen, nicht dass das script der Meinung ist nicht updaten zu müssen

**Comment by scripthase** [comment]
> Ja, du kannst in der Fritzbox in der URL die parameter einfach mit angeben: https:///update.php?user=&password=&domain=&force=true&mode=both

Alles klar, habe ich mal mit angegeben. Schauen wir Mal, ob es dann jetzt funktioniert.

> Und in der .env auf dem Webserver mal debug=true setzen

Das habe ich sowieso von Anfang an schon aktiviert. :)

**Comment by scripthase** [comment]
Habe direkt Mal ins Log geschaut und da steht jetzt drin:
```
"[2023-08-23T12:35:02+02:00] api login successful",
"[2023-08-23T12:35:02+02:00] IPv4 for *.***.eu set to 91.**.**.**",
"[2023-08-23T12:35:02+02:00] IPv4 for @.***.eu set to 91.**.**.**",
"[2023-08-23T12:35:02+02:00] dns recordset updated",
"[2023-08-23T12:35:02+02:00] api logout successful"
```

Scheint also, dass es jetzt funktioniert.
Ich beobachte Mal, wie lange das jetzt so funktioniert.

Vielen lieben Dank schon Mal!
