### ISSUE TITLE
Fehlermeldung in der Fritz!Box nach erfolgreichen updaten der IP

### ISSUE THREAD

**Issue by nillebor** [fernwerker/ownDynDNS#30]
Ich habe dein Script im Einsatz auf einer Synology DS. Das funktioniert auch ganz gut und zuverlässig.
Nach der täglichen Zwangstrennung bekomme ich im Log der Fritz!Box aber einen Fehler gelistet:
`DynDNS-Fehler: Die DynDNS-Aktualisierung war erfolgreich, anschließend trat jedoch ein
Fehler bei der DNS-Auflösung auf.`

AVM schreibt dazu: "Die Aktualisierungsanforderung wurde vom DynDNS-Anbieter bestätigt, aber technisch noch nicht umgesetzt. Nach einigen Minuten erfolgt die Umstellung Ihrer IP-Adresse automatisch. Bei Bedarf können Sie dies überprüfen, indem Sie Ihre Domain im Browser aufrufen.

Einige DNS-Server im Internet aktualisieren die Zuordnung von IP-Adressen zu Domainnamen nicht unmittelbar. Sie beantworten Anfragen zu Dynamic-DNS-Domainnamen dadurch noch eine Zeit lang mit einer alten IP-Adresse, obwohl die FRITZ!Box dem Dynamic-DNS-Anbieter bereits eine neue IP-Adresse mitgeteilt hat. Dieses Verhalten der DNS-Server kann weder von der FRITZ!Box noch von Ihrem Dynamic-DNS-Anbieter beeinflusst werden."

Kann man den Fehler irgendwie ausschalten bzw. fixen oder ist es bedingt durch die Wartezeit bis die IP bei Netcup durchgelaufen ist?

**Comment by fernwerker** [comment]
What’s the TTL (time to live) value in your netcup domain?
I usually set this to 10min to have faster refresh rates on domains with dynamic hosts.

**Comment by nillebor** [comment]
TTL=300 also 5 Minuten.

**Comment by fernwerker** [comment]
Question for the setup: the php is running in the Synology and does DNS APIs towards netcup servers?
I’d go for hosting it within netcups network on a web host to isolate the API calls more. But ok. 

The message from FRITZ!box is most likely because of the updating time of DNS so might also be that your ISP DNS just takes too long to update and your FRITZ!box is complaining. 

For testing you can point your FRITZ!box to public dns servers such as googles 8.8.8.8 and see if this also resolved into the message. 
Nevertheless, if it’s working I wouldn’t care too much, although I’m also Someone trying to reduce log messages. ;-)

**Comment by nillebor** [comment]
Danke für die Antwort.

Ich habe nur eine Netcup-Domain, welche es regelmäßig für 13ct pro Monat gibt. Ein Webhosting-Tarif mit Webspace habe ich nicht.

Generell funktioniert es auch ohne Probleme und ich habe eher Netcup wegen der Geschwindigkeit im Blickwinkel. Bei mir braucht Netcup trotzt TTL300 ca. 10 Minuten um die IP anzupassen. Die Fehlermeldung kommt etwas 12-14 Minuten nach dem Update von der Fritz!Box. Wie AVM die Validierung macht, werde ich mir noch einmal genau ansehen und die Logs überprüfen.

Ansonsten hast du natürlich recht das es nur ein "Schönheitsfehler" ist und es nicht ins Gewicht fällt. Viel schlimmer finde ich die Zeiten von Netcup bis es, durch deren System durchgelaufen ist und dass es kein DynDNS direkt gibt. Mit deinen Script kann man aber sehr gut leben. Eine aktuelle Docker-Version wäre nicht schlecht und versuche es gerade umzusetzen, sofern ich ein bisschen mehr Zeit finde.

Indexstand wäre noch die Möglichkeit nicht nur @, sondern auch * in Netcup zu aktualisieren und das in der .env als zusätzliche Variable zu hinterlegen: @, * oder beide.

Sofern ich etwas mehr weis, kann ich es gerne hier schreiben. Danke für deine Hilfe und Script!

**Comment by fernwerker** [comment]
It does not need to be netcup. This can also be the refreshing rates of your ISP DNS cache or any DNS server in between. 
DNS is a distributed system so not always the root server has to be queried but every server caches the queries once done. 

So try an external public DNS server in your FRITZ!box Internet connection and see what happens.
