### ISSUE TITLE
Not working anymore - problem with xmlsoap

### ISSUE THREAD

**Issue by mlte116** [fernwerker/ownDynDNS#31]
Hi,
since today I am facing the following error while using the update.php

`Fatal error: Uncaught SoapFault exception: [SOAP-ERROR: Parsing Schema: can't import schema from 'http://schemas.xmlsoap.org/wsdl/soap/'] WSDL in /var/www/vhosts/hosting.xxx.netcup.net/cloud.x-x.de/httpdocs/dyndns/src/Soap.php:44
Stack trace:
#0 /var/www/vhosts/hosting.xxx.netcup.net/cloud.x-x.de/httpdocs/dyndns/src/Soap.php(130): netcup\DNS\API\Soap\DomainWebserviceSoapClient::_Call()
#1 /var/www/vhosts/hosting.xxx.netcup.net/cloud.x-x.de/httpdocs/dyndns/src/Handler.php(103): netcup\DNS\API\Soap\DomainWebserviceSoapClient->login()
#2 /var/www/vhosts/hosting200730..netcup.net/cloud.x-x.de/httpdocs/dyndns/update.php(31): netcup\DNS\API\Handler->doRun()
#3 {main}
  thrown in /var/www/vhosts/hosting.xxx.netcup.net/cloud.x-x.de/httpdocs/dyndns/src/Soap.php on line 44`

I tried to access xmlsoap manually but it seems to be in issue on their side. Could it be possible to import the parsing scheme into the code, so the tool does not rely to an external service?

Thanks and BR
Malte

**Comment by nillebor** [comment]
The same here for a few days. netcup has "supposedly" changed nothing. Owndyndns worked for months without problems. 
Please fix it.

**Comment by fernwerker** [comment]
I'm sorry, but I do have limited time to fix this currently.
This is a proposal that might work, but I've not tested this. So maybe you can test this by replacing line 37-46 in Soap.php by this:

`public static function _Call($method, $param) {
    try {
        if (is_null(self::$_Server)) {
            // Update the WSDL namespace URI to WSDL 2.0
            self::$_Server = new SoapClient(null, array('location' => self::$_WsdlUri, 'uri' => 'http://www.w3.org/ns/wsdl/'));
        }
        return self::$_Server->__soapCall($method, $param);
    } catch (Exception $exception) {
        throw new SoapFault($exception->faultstring, $exception->faultcode, $exception);
    }
}
`

**Comment by mlte116** [comment]
Hi Felix
thank you a lot for the feedback. I will try this!

BR
Malte

Felix Kretschmer ***@***.***> schrieb am Do., 2. Mai 2024,
11:31:

**Comment by nillebor** [comment]
I replaced the lines.
Now comes this error message:
`Parse error: syntax error, unexpected token "public" in /volume1/web/ownDynDNS/src/Soap.php on line 52`

**Comment by Asfaroth** [comment]
I had the same issue but since a few days it started working again. I guess netcup fixed the issue on their side.

**Comment by reiter-ja** [comment]
Same here. Maybe because of this:

https://www.heise.de/news/Content-Delivery-Network-JSDelivr-Ausfall-trifft-zahlreiche-Websites-9705222.html

**Comment by nillebor** [comment]
Thanks for the tip. It's working again. Owndyndns works again with the original files. I myself asked Netcup by phone if there is a problem.

In the meantime I have a redirect to a dyndns (dynv6.com ) is established. Unfortunately, the Netcup does not have DynDNS as it has been promoted several times.

Problem is solved for me first of all. Have a nice Sunday :)

**Comment by fernwerker** [comment]
My strategy worked out: just wait and see. ;-)

thanks for the responses
