### ISSUE TITLE
Handle IPv6 hosts behind router

### ISSUE THREAD

**Issue by fernwerker** [fernwerker/ownDynDNS#4]
Problem:
  * Fritzbox has IPv4 and IPv6 address and publishes them to fritzbox.example.com.
  * You have additional hosts in your network, that you want to reach (e.g. NAS, etc.) via IPv4 port forwarding and native IPv6
  * IPv4 is easy and can be solved by this script. Parallel IPv6 is difficult, because the IPv6 address is the one of the fritzbox and not of your host behind the fritzbox
  * Especially for using services like Let's Encrypt this is a challenge

Approach:
  * Separate host and router with domains:
    * fritzbox.example.com -> A record from router, AAAA record from router
    * nas.example.com -> A record from router, AAAA record from host
  * CNAME and AAAA record for one host is not a valid solution and ALIAS is not supported by netcup (yet)
 
Solution:
  * Extend script with a parameter to define additional domains that need to be updated with the IPv4 address
  * Use script for additional hosts (e.g. NAS) as well to update AAAA entry for host only

Expected behavior:
  * update.php works as before and additionally there is a parameter like "addv4=<host1>,<host2>,etc.

**Comment by b2un0** [comment]
Noch zu wenig Kaffee um hier in Englisch zu antworten - man vergebe mir.

Das Problem habe ich auch, lässt sich aber relativ einfach lösen wenn man dieses Script hier soweit anpassen würde das es kein force update bei NC macht sondern vorher prüft ob die IPs im DNS Response nicht noch die gleichen sind (durchaus möglich das ich nach reinem Reconnect die gleiche IPv4 erhalte!). > https://github.com/stecklars/dynamic-dns-netcup-api/blob/master/update.php#L90

Dann könnte man dieses Script hier auch wie folgt direkt vom NAS aufrufen.

Aktuell verwende ich auf meinem NAS das `dynamic-dns-netcup-api` von `stecklars`, ich möchte aber die PHP Abhängigkeit entfernen weswegen ich hier gelandet bin.
Mein Problem ist das hier der Check fehlt ob sich die IP überhaupt geändert hat, ich möchte die DNS API von NC halt nicht penetrieren - Stichwort etwaige rate limits in Zukunft.

```bash
#!/usr/bin/env bash

USER="max_mustermann"
PASS="s3cr3t"
DOMAIN="domain.tld"

IPV4=$(curl -4 -q ifconfig.me)
IPV6=$(curl -6 -q ident.me)

echo $IPV4
echo $IPV6

URL="https://<url of your webspace>/.well-known/dns/update.php?user=${USER}&password=${PASS}&ipv4=${IPV4}&ipv6=${IPV6}&domain=${DOMAIN}"

curl ${URL}
```

Ein nettes feature wäre im übrigen wenn das Script hier Daten aus `$_REQUEST` entgegen nimmt statt hard aus `$_GET` - dann könnt man auch per `$_POST` mittels `curl` anfragen und die Daten würden nicht im Access Log des Servers landen.

**Comment by fernwerker** [comment]
Guter Input. Freue mich über pull requests. :)
Ich muss schauen, was meine Zeit in den nächsten Wochen zu lässt. Das Projekt war damals durch verfügbare Zeit und Motivation getrieben. Nachdem es läuft und die Zeit gerade knapp ist, schleift es etwas.

**Comment by b2un0** [comment]
@fernwerker kannst du mir nebenher erklären wofür die Methode `reduceHost` genau da ist?
Also was genau hat die für einen Sinn?

**Comment by fernwerker** [comment]
Ich hab zwar ne Mail bekommen, sehe aber deinen comment nicht.
Zum Thema "//Has the IP changed?" fiel mir noch ein, dass das Skript ursprünglich für die Fritzbox entworfen wurde. Die löst ohnehin nur aus, wenn die IP oder DynDNS Einstellungen geändert wurden.
Für andere Einsatzzwecke macht das aber Sinn und tut der Funktion für die Fritzbox natürlich keinen Abbruch.

**Comment by b2un0** [comment]
Ja, ich hatte den Kommentar wieder gelöscht nach dem ich verstanden hab wofür die Funktion da ist.

dieses Script ist halt in Verbindung mit IPv6 echt ein Problem weswegen ich es nicht über die Fritte verwende.

Ich nutze für DynDNS keine Sub Domain sondern eine eigens für mein NAS registrierte Domain.
Daher, ich möchte das der AAA Rekord direkt auf die IPv6 des NAS zeigt - wenn dieser auf die Fritte zeigt funktionieren diverse Dienste nicht über IPv6.

Ich schreib das Script aber gerade um - ist leider ein größerer Aufriss.

**Comment by fernwerker** [comment]
Cooler Input. Habs akzeptiert und wollte dabei eigentlich meine Änderungen als Review einbringen, hatte aber den commit meiner Änderungen vergessen. Bin durch das Projekt am git und php lernen. :-)
Danke auf jeden Fall für den umfangreichen Input.

**Comment by b2un0** [comment]
Kein Thema.

Das Issue hier sollte eigentlich auch damit erledigt sein.
Man muss die `update.php` halt direkt vom NAS aufrufen da du über die FB nie an sauber (!) an die korrekte IPv6 kommen wirst.

Theoretisch müsste man das sogar z.B. im DSM eines Synolgy NAS über den DynDNS Client regeln können.

**Comment by fernwerker** [comment]
Das geht im DSM tatsächlich. Habe ich schon mal angeschaut.
Meine ursprüngliche Idee war ja, dass die v4 Adresse weiterer Hosts durch die Fritzbox geändert wird, da die ja am frühesten den Reconnect merkt und ich die v4 nicht durch das NAS pushen lasse, sondern nur die v6.
Aber man kann auch einfach beide über das NAS machen. Ist eine isoliertere Struktur.

**Comment by pReya** [comment]
Sorry for barging in here, even though this issue has been closed. I'm working on the same problem: I want to call this script from my Synology NAS, preferably using the onboard DynDNS-Function (I know I can always run it as a shell script or in a container). And while the DSM supports custom DynDNS-Providers (yay!), it seems to me that DSM will not submit the current IPv6 address, but only the IPv4 address.

They only have one Parameter in the query builder UI which is called `__MYIP__` and it seems to only submit the IPv4. Even worse: When using their very own `synology.me` service, IPv6 will magically work. So it seems they're artificially limiting the featureset for Non-Synology DynDNS Providers. Can anyone confirm this?

**Comment by b2un0** [comment]
@pReya  if you have docker installed, you can try me yesterday released docker container for this scenario.

https://github.com/b2un0/docker-netcup-dyndns

**Comment by pReya** [comment]
@b2un0 Thanks! I'll definitely get back to this, if I can't get ir working with the builtin DynDNS function. But I'd really like to avoid spinning up a container for such a simple task.

**Comment by fernwerker** [comment]
If you found a solution to get the v6 variable from synology (by design and not with manual work-around), please let us know. Would be interessted in as well.
Was looking through the internet myself and didn't find anything. Just solutions with a bash script that greps it from the interface.

**Comment by b2un0** [comment]
> @b2un0 But I'd really like to avoid spinning up a container for such a simple task.
thats the reason why i build a slim container (83MB).

**Comment by pReya** [comment]
Still, 83MB to fire a simple http request seems weird to me.

**Comment by fernwerker** [comment]
Technisch gesehen ist das auf jeden Fall möglich. Ich stele mir das auch ganz ähnlich zu Dynv6 vor.
Bspw. man definiert ein feste Hosts im v6 Prefix anhand der MAC und ownDynDNS aktualisiert dann den Prefix via netcup für alle definierten hosts.

Alles machbar.
Die Umsetzung ist leider auch eine Zeitfrage und die kann ich aktuell nicht stemmen, bin aber für PRs jederzeit offen und nehme mir dann gerne auch die Zeit fürs Review.

Wenn jemand die Weihnachtspause nutzen möchte, um Technologien wie ChatGPT etc. zu erfahren --> kann ich persönlich für solche Projekte empfehlen und reduziert die Umsetzungszeit.

**Comment by fernwerker** [comment]
Super wäre natürlich den Code auf Funktion zu prüfen und anschließend als Pull Request (PR) im repository zu erstellen, damit man ihn reviewen und mergen kann.
