### ISSUE TITLE
DNS-record is needed before testing the script

### ISSUE THREAD

**Issue by goermezer** [fernwerker/ownDynDNS#6]
The script can only update existing records. You first have to create the DNS record in customer control panel at Netcup. Then you can install and execute the script.

Otherwise it simply prints: dns recordset NOT updated (no changes)

**Comment by fernwerker** [comment]
Yes. That’s the intended behavior as written in the Readme:
„Create each host record in your netcup CCP before using the script. The script does not create any missing records.“

So in case of misconfigurarion or something the script does not overload the api with record creation.

**Comment by tefracky** [comment]
Hello,
which DNS record has to be created?

**Comment by fernwerker** [comment]
The one you want to run your dynamic host on.

**Comment by tefracky** [comment]
Okay, so lets say I have a domain test.de I want to redirect to my Fritzbox. Which DNS records have to be created exactly at the CCP?

**Comment by fernwerker** [comment]
Well, I didn't design the script for second level but more for third level domains.
It might work with second level as well, but you might have to check on it.
The entry would be the "@" entry within CCP.

**Comment by tefracky** [comment]
No problem, I could also use a domain sub.test.de. Which DNS records have to be created then?

**Comment by fernwerker** [comment]
An A record for IPv4 and an AAAA for IPv6
