### ISSUE TITLE
: Datei oder Verzeichnis nicht gefunden

### ISSUE THREAD

**Issue by alandolsi** [fernwerker/ownDynDNS#7]
ich bekomme diese fehler beim ausführen der Script update-dyndns.sh, habe ich was falsches?
: Datei oder Verzeichnis nicht gefunden

**Comment by b2un0** [comment]
bitte einen Screenshot oder Consolen Output anhängen was und vor allen in welchen Pfad du es ausführst.

**Comment by alandolsi** [comment]
![image](https://user-images.githubusercontent.com/3594182/63579994-1898a780-c594-11e9-83a6-1c05a7cea891.png)

**Comment by fernwerker** [comment]
Kannst du bitte mal den Inhalt der update-dyndns.sh posten und davor deine sensiblen Informationen (Passwörter, Usernames, etc.) zensieren.

**Comment by alandolsi** [comment]
![image](https://user-images.githubusercontent.com/3594182/63580864-fef85f80-c595-11e9-8368-7a45a2f588b4.png)

**Comment by fernwerker** [comment]
Ich sehe auf Anhieb nichts und kann gerade selbst nicht testen, ob `#!/usr/bin/env bash` auf einer netcup Shell läuft.
Ich würde daher mal in verschiedenen Zeilen ein `echo 'DEBUG'` einbauen und schauen wo denn der fehlerhafte Aufruf passiert.
Könnte sein, dass `#!/usr/bin/env bash` nicht geht. Und du es mit `#!/bin/bash` zum laufen bekommst.

**Comment by b2un0** [comment]
Nur fürs Verständnis:
die `update-dyndns.sh` kommt auf ein *nix based Device in deinem Haus Netzwerk (z.b. ein RPI / NAS).

die `update.php` muss dann für die `update-dyndns.sh` erreichbar sein! entweder über das gleiche Gerät mittels `localhost` oder auf einem WebServer wo du die `update.php` inkl `src` Ordner und `.env` Datei abgelegt hast.

Für mich sieht das aber so aus als wäre `curl` nicht installiert..

**Comment by alandolsi** [comment]
Danke für eure Hilfe, ich werde das testen

**Comment by alandolsi** [comment]
Problem gelöst, es war ein Missverständnis von mir.
